"""
Shannon ↔ OpenClaw integration.

How it works:
  1. During a session, call `save()` to persist important context to Shannon.
  2. At session end / on compression, call `compress_session()` to flush
     everything worth keeping.
  3. At session start, OpenClaw reads memory/shannon-context.md — this file
     is regenerated by `generate_context_file()` and contains the most
     relevant recent Shannon chunks, ready to inject into context.

The bridge: Shannon writes to disk, context file bridges back into
the OpenClaw workspace file system that Guy reads at every session start.
"""

import json
import hashlib
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import List, Optional

from .store import write, get_session_chunks, stats, init_store, _connect

WORKSPACE = Path.home() / ".openclaw" / "workspace"
CONTEXT_FILE = WORKSPACE / "memory" / "shannon-context.md"
MAX_CONTEXT_CHUNKS = 30       # chunks to surface at session start
MAX_CHUNK_CHARS   = 2_000     # truncate very long chunks


# ---------------------------------------------------------------------------
# Save — call this during a session to persist something important
# ---------------------------------------------------------------------------

def save(text: str, session_id: str, tags: List[str] = None) -> str:
    """
    Persist a context chunk to Shannon.
    Returns the Zeckendorf address.

    Call this when something worth remembering happens:
      - Key decisions made
      - Architecture discussions
      - Project milestones
      - Anything you'd put in MEMORY.md but more granular
    """
    return write(text, session_id=session_id, tags=tags or [])


# ---------------------------------------------------------------------------
# Compress session — flush a list of chunks at once (e.g. on context pressure)
# ---------------------------------------------------------------------------

def compress_session(chunks: List[str], session_id: str,
                     tags: List[str] = None) -> List[str]:
    """
    Persist multiple context chunks in one call.
    Returns list of addresses.

    Use this when context window fills — instead of discarding, write to Shannon.
    """
    return [save(chunk, session_id, tags) for chunk in chunks if chunk.strip()]


# ---------------------------------------------------------------------------
# Generate context file — run at session end, read at session start
# ---------------------------------------------------------------------------

def generate_context_file(
    days_back: int = 7,
    max_chunks: int = MAX_CONTEXT_CHUNKS,
    session_id: Optional[str] = None,
) -> Path:
    """
    Build memory/shannon-context.md from recent Shannon entries.

    This file is automatically read by Guy at session start via AGENTS.md,
    injecting persistent memory into each new session.
    """
    init_store()
    conn = _connect()

    cutoff = (datetime.now(timezone.utc) - timedelta(days=days_back)).isoformat()

    query = """
        SELECT content_hash, address, created_at, session_id, tags
        FROM entries
        WHERE created_at >= ?
        ORDER BY created_at DESC
        LIMIT ?
    """
    params = [cutoff, max_chunks]

    if session_id:
        query = query.replace("WHERE created_at >= ?",
                              "WHERE created_at >= ? AND session_id = ?")
        params = [cutoff, session_id, max_chunks]

    rows = conn.execute(query, params).fetchall()
    conn.close()

    if not rows:
        content = _empty_context()
    else:
        content = _render_context(rows)

    CONTEXT_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONTEXT_FILE.write_text(content)
    return CONTEXT_FILE


def _render_context(rows) -> str:
    from .store import read_by_hash

    lines = [
        "# Shannon Context — Persistent Memory",
        f"_Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} "
        f"· {len(rows)} chunks · Layer 1 Tesseract_",
        "",
    ]

    for row in rows:
        chunk = read_by_hash(row["content_hash"])
        if not chunk:
            continue

        if len(chunk) > MAX_CHUNK_CHARS:
            chunk = chunk[:MAX_CHUNK_CHARS] + "…"

        tags = json.loads(row["tags"] or "[]")
        tag_str = f" `{'` `'.join(tags)}`" if tags else ""
        ts = row["created_at"][:10]
        session = row["session_id"] or "unknown"

        lines += [
            f"---",
            f"**{ts}** · session `{session}`{tag_str}",
            f"**Address:** `{row['address'][:60]}…`",
            "",
            chunk,
            "",
        ]

    s = stats()
    lines += [
        "---",
        f"_Shannon dictionary: {s['total_entries']} entries · "
        f"{s['total_mb_raw']} MB stored · capacity: {s['capacity']}_",
    ]

    return "\n".join(lines)


def _empty_context() -> str:
    return (
        "# Shannon Context — Persistent Memory\n\n"
        "_No entries yet. Shannon is ready to remember._\n"
    )


# ---------------------------------------------------------------------------
# CLI — run directly to regenerate context file
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    days = int(sys.argv[1]) if len(sys.argv) > 1 else 7
    path = generate_context_file(days_back=days)
    s = stats()
    print(f"Context file written: {path}")
    print(f"Dictionary: {s['total_entries']} entries, {s['total_mb_raw']} MB")
