"""
Shannon ↔ OpenClaw integration.

How it works:
  1. During a session, call `save()` to persist important context to Shannon.
  2. At session end / on compression, call `compress_session()` to flush
     everything worth keeping.
  3. At session start, OpenClaw reads memory/shannon-context.md — this file
     is regenerated by `generate_context_file()` and contains the most
     relevant recent Shannon chunks, ready to inject into context.

The bridge: Shannon writes to disk, context file bridges back into
the OpenClaw workspace file system that Guy reads at every session start.
"""

import json
import hashlib
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import List, Optional

from .store import write, get_session_chunks, stats, init_store, _connect

WORKSPACE = Path.home() / ".openclaw" / "workspace"
CONTEXT_FILE = WORKSPACE / "memory" / "shannon-context.md"
MAX_CONTEXT_CHUNKS = 50       # max chunks to pull from DB
MAX_CHUNK_CHARS   = 2_000     # truncate very long chunks

# Time-tiered rendering thresholds
HOT_HOURS   = 48    # 0-48h: full detail per chunk
WARM_DAYS   = 7     # 48h-7d: grouped by session, truncated
COLD_DAYS   = 30    # 7-30d: session headers only (date + name + tags)
WARM_CHARS  = 500   # max chars per session in warm tier


# ---------------------------------------------------------------------------
# Save — call this during a session to persist something important
# ---------------------------------------------------------------------------

def save(text: str, session_id: str, tags: List[str] = None) -> str:
    """
    Persist a context chunk to Shannon.
    Returns the Zeckendorf address.

    Call this when something worth remembering happens:
      - Key decisions made
      - Architecture discussions
      - Project milestones
      - Anything you'd put in MEMORY.md but more granular
    """
    return write(text, session_id=session_id, tags=tags or [])


# ---------------------------------------------------------------------------
# Compress session — flush a list of chunks at once (e.g. on context pressure)
# ---------------------------------------------------------------------------

def compress_session(chunks: List[str], session_id: str,
                     tags: List[str] = None) -> List[str]:
    """
    Persist multiple context chunks in one call.
    Returns list of addresses.

    Use this when context window fills — instead of discarding, write to Shannon.
    """
    return [save(chunk, session_id, tags) for chunk in chunks if chunk.strip()]


# ---------------------------------------------------------------------------
# Generate context file — run at session end, read at session start
# ---------------------------------------------------------------------------

def generate_context_file(
    days_back: int = COLD_DAYS,
    max_chunks: int = MAX_CONTEXT_CHUNKS,
    session_id: Optional[str] = None,
) -> Path:
    """
    Build memory/shannon-context.md from recent Shannon entries.
    Uses time-tiered rendering:
      - Hot (0-48h): full detail per chunk
      - Warm (48h-7d): grouped by session, truncated
      - Cold (7-30d): session headers only
    """
    init_store()
    conn = _connect()

    cutoff = (datetime.now(timezone.utc) - timedelta(days=days_back)).isoformat()

    query = """
        SELECT content_hash, address, created_at, session_id, tags
        FROM entries
        WHERE created_at >= ?
        ORDER BY created_at DESC
        LIMIT ?
    """
    params = [cutoff, max_chunks]

    if session_id:
        query = query.replace("WHERE created_at >= ?",
                              "WHERE created_at >= ? AND session_id = ?")
        params = [cutoff, session_id, max_chunks]

    rows = conn.execute(query, params).fetchall()
    conn.close()

    if not rows:
        content = _empty_context()
    else:
        content = _render_tiered_context(rows)

    CONTEXT_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONTEXT_FILE.write_text(content)
    return CONTEXT_FILE


def _render_tiered_context(rows) -> str:
    """Render chunks in time-tiered format: hot (full), warm (grouped), cold (headers)."""
    from .store import read_by_hash

    now = datetime.now(timezone.utc)
    hot_cutoff = now - timedelta(hours=HOT_HOURS)
    warm_cutoff = now - timedelta(days=WARM_DAYS)

    hot, warm, cold = [], [], []
    for row in rows:
        ts = row["created_at"]
        # Parse timestamp — handle both aware and naive
        try:
            dt = datetime.fromisoformat(ts)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
        except (ValueError, TypeError):
            dt = now  # fallback: treat as hot
        if dt >= hot_cutoff:
            hot.append(row)
        elif dt >= warm_cutoff:
            warm.append(row)
        else:
            cold.append(row)

    total = len(hot) + len(warm) + len(cold)
    lines = [
        "# Shannon Context — Persistent Memory",
        f"_Generated {now.strftime('%Y-%m-%d %H:%M UTC')} "
        f"· {total} entries · Tiered: {len(hot)} hot / {len(warm)} warm / {len(cold)} cold_",
        "",
    ]

    # --- HOT: full detail ---
    if hot:
        lines += ["## 🔥 Hot (last 48h) — full detail", ""]
        for row in hot:
            chunk = read_by_hash(row["content_hash"])
            if not chunk:
                continue
            if len(chunk) > MAX_CHUNK_CHARS:
                chunk = chunk[:MAX_CHUNK_CHARS] + "…"
            tags = json.loads(row["tags"] or "[]")
            tag_str = f" `{'` `'.join(tags)}`" if tags else ""
            ts = row["created_at"][:10]
            session = row["session_id"] or "unknown"
            lines += [
                f"---",
                f"**{ts}** · session `{session}`{tag_str}",
                "",
                chunk,
                "",
            ]

    # --- WARM: grouped by session, truncated ---
    if warm:
        lines += ["## 🟡 Warm (2-7 days) — session summaries", ""]
        # Group by session_id
        sessions = {}
        for row in warm:
            sid = row["session_id"] or "unknown"
            if sid not in sessions:
                sessions[sid] = {"rows": [], "tags": set(), "date": row["created_at"][:10]}
            sessions[sid]["rows"].append(row)
            for t in json.loads(row["tags"] or "[]"):
                sessions[sid]["tags"].add(t)

        for sid, info in sessions.items():
            tag_str = f" `{'` `'.join(sorted(info['tags']))}`" if info["tags"] else ""
            lines += [f"---", f"**{info['date']}** · `{sid}`{tag_str} ({len(info['rows'])} chunks)"]
            # Merge chunks for this session, truncate to WARM_CHARS
            merged = ""
            for row in info["rows"]:
                chunk = read_by_hash(row["content_hash"])
                if chunk:
                    merged += chunk + "\n"
                if len(merged) >= WARM_CHARS:
                    break
            if len(merged) > WARM_CHARS:
                merged = merged[:WARM_CHARS] + "…"
            lines += ["", merged.strip(), ""]

    # --- COLD: headers only ---
    if cold:
        lines += ["## 🧊 Cold (7-30 days) — reference only", ""]
        seen_sessions = set()
        for row in cold:
            sid = row["session_id"] or "unknown"
            if sid in seen_sessions:
                continue
            seen_sessions.add(sid)
            tags = json.loads(row["tags"] or "[]")
            tag_str = f" · {', '.join(tags)}" if tags else ""
            ts = row["created_at"][:10]
            lines.append(f"- **{ts}** `{sid}`{tag_str}")
        lines.append("")

    s = stats()
    lines += [
        "---",
        f"_Shannon dictionary: {s['total_entries']} entries · "
        f"{s['total_mb_raw']} MB stored · capacity: {s['capacity']}_",
        f"_Tiers: hot={HOT_HOURS}h / warm={WARM_DAYS}d / cold={COLD_DAYS}d · "
        f"Full chunks always in store for on-demand retrieval._",
    ]

    return "\n".join(lines)


def _empty_context() -> str:
    return (
        "# Shannon Context — Persistent Memory\n\n"
        "_No entries yet. Shannon is ready to remember._\n"
    )


# ---------------------------------------------------------------------------
# CLI — run directly to regenerate context file
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    days = int(sys.argv[1]) if len(sys.argv) > 1 else 7
    path = generate_context_file(days_back=days)
    s = stats()
    print(f"Context file written: {path}")
    print(f"Dictionary: {s['total_entries']} entries, {s['total_mb_raw']} MB")
